In [2]:
import numpy as np
import random
import matplotlib.pyplot as plt

In [7]:
def create_data():
    train_data = [[[3,3], 1], [[2, 2], 1], [[1, 1], -1]]
    feature = []
    label = []
    for item in train_data:
        feature.append(item[0])
        label.append(item[1])
    feature = np.array(feature)
    label = np.array(label)
    return feature, label


[[3 3]
 [2 2]
 [1 1]]
[ 1  1 -1]


In [12]:
class perceptron:
    def __init__(self, feature, label):
        self.w = np.array([0, 0])
        self.b = 0
        self.lr = 1
        self.feature = feature
        self.label = label
    
    def update(self, x, y):
        self.w = self.w + self.lr * y * x
        self.b = self.b + self.lr * y
        
    def sign(self, x, y):
        return np.sign((np.dot(self.w, x) + self.b) * y)
    
    def train(self):
        flag = True
        while flag:
            flag = False
            for i in range(len(self.feature)):
                if self.sign(self.feature[i], self.label[i]) <= 0:
                    print("误分点：", self.feature[i])
                    self.update(self.feature[i], self.label[i])
                    flag = True
        print("最终参数：w:",self.w, " b:", self.b)
        return self.w, self.b


In [13]:
feature, label = create_data()
p = perceptron(feature, label)
p.train()

误分点： [3 3]
误分点： [1 1]
误分点： [1 1]
误分点： [1 1]
误分点： [3 3]
误分点： [1 1]
误分点： [1 1]
最终参数：w: [1 1]  b: -3


(array([1, 1]), -3)

In [34]:
class dual_perceptron:
    def __init__(self, feature, label):
        self.lr = 1
        self.b = 0
        self.feature = feature
        self.label = label
        self.a = np.zeros(len(feature))
        self.gram = np.zeros([len(feature), len(feature)])
        for i in range(len(feature)):
            for j in range(len(feature)):
                self.gram[i][j] = np.dot(feature[i], feature[j])
        print(self.gram)
    
    def update(self, idx):
        self.a[idx] += self.lr
        self.b += self.lr * self.label[idx]
        
    def sign(self, idx):
        res = 0
        for i in range(len(self.feature)):
            res += self.a[i] * self.label[i] * self.gram[idx][i]
        return np.sign((res + self.b) * self.label[idx])
    
    def train(self):
        flag = True
        while flag:
            flag = False
            for i in range(len(self.feature)):
                if self.sign(i) <= 0:
                    print("更新feature：", self.feature[i], " 更新前a：", self.a, " 更新前b:", self.b)
                    self.update(i)
                    print(" 更新后a：", self.a, " 更新后b:", self.b)
                    flag = True
        w = [0,0]
        for i in range(len(self.feature)):
            w += self.a[i] * self.feature[i] * self.label[i]
        print("训练结束：w:", w, " b:", self.b)
        return w, self.b

In [35]:
feature[1] = np.array([4,3])
d_p = dual_perceptron(feature, label)
d_p.train()

[[18. 21.  6.]
 [21. 25.  7.]
 [ 6.  7.  2.]]
更新feature： [3 3]  更新前a： [0. 0. 0.]  更新前b: 0
 更新后a： [1. 0. 0.]  更新后b: 1
更新feature： [1 1]  更新前a： [1. 0. 0.]  更新前b: 1
 更新后a： [1. 0. 1.]  更新后b: 0
更新feature： [1 1]  更新前a： [1. 0. 1.]  更新前b: 0
 更新后a： [1. 0. 2.]  更新后b: -1
更新feature： [1 1]  更新前a： [1. 0. 2.]  更新前b: -1
 更新后a： [1. 0. 3.]  更新后b: -2
更新feature： [3 3]  更新前a： [1. 0. 3.]  更新前b: -2
 更新后a： [2. 0. 3.]  更新后b: -1
更新feature： [1 1]  更新前a： [2. 0. 3.]  更新前b: -1
 更新后a： [2. 0. 4.]  更新后b: -2
更新feature： [1 1]  更新前a： [2. 0. 4.]  更新前b: -2
 更新后a： [2. 0. 5.]  更新后b: -3
训练结束：w: [1. 1.]  b: -3


(array([1., 1.]), -3)

In [27]:
t = np.array([1,1])
print(np.dot([2,1], t))
print(sum([[2,1],[1,1]]))

3


TypeError: unsupported operand type(s) for +: 'int' and 'list'